# Generated by Django 4.2.5 on 2023-10-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"permissions": (("can_undelete", "Can undelete this object"),)},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="message",
            name="order",
        ),
        migrations.AddField(
            model_name="conversation",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
