# Generated by Django 4.2.5 on 2023-10-14 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_rename_current_version_conversation_active_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="active",
        ),
    ]
