# Generated by Django 4.2.5 on 2023-10-14 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_remove_conversation_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="active_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_version_conversations",
                to="chat.version",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="root_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="root_message_versions",
                to="chat.message",
            ),
        ),
    ]
