# Generated by Django 4.2.5 on 2023-11-01 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_alter_conversation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="versions", to="chat.conversation"
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="parent_version",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="chat.version"
            ),
        ),
    ]
