# Generated by Django 4.2.5 on 2023-11-01 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_alter_version_conversation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="chat.conversation"
            ),
        ),
    ]
