# Generated by Django 4.2.5 on 2023-11-20 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_alter_version_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
