# Generated by Django 4.2.5 on 2023-11-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_alter_conversation_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
